### ISSUE TITLE
Fix Multiple choice so that it only shows on it's state

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game#11]
Multiple choice remains on screen after it is activated. Have it only appear on Beginner state.

**Comment by tiagodcosta** [comment]
@JSmith92 Yogesh is working on this bug

**Comment by tiagodcosta** [comment]
Fixed with 53083dcfaeab111e228d2a7ab1f9a62770cb9cea and 0d1f7ca794f957031920e8d0869fca72f93961e8
