### ISSUE TITLE
style error in beginning of preview

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game#17]
May be the reason for the "document.getElementByClassName()" crash.
6: Uncaught TypeError: Cannot read property 'style' of null
"p5 had problems creating the global function \"text\", possibly because your code is already using that name as a variable. You may want to rename your variable to something else."

**Comment by tiagodcosta** [comment]
Fixed with f47c3ece031292cff3c378f3e4381b03b8eb3fb8
