### ISSUE TITLE
End Game "Return Main Menu" button action error

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/writing-game#177]
232: Uncaught TypeError: Cannot read property 'style' of null

the code causing error: 
  action.js

line 232:
document.getElementById("letterOptions").style.display="inline-block";
  var nodes = document.getElementById("ce__container").getElementsByTagName('*');
  for(var i = 0; i < nodes.length; i++){
     nodes[i].disabled = false;
  }

**Comment by tiagodcosta** [comment]
Fixed with f5ed23119765b0969f31c2063fa1a70e57821f35
