### ISSUE TITLE
Julie video

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#334]
Julie made those videos, so we should be able to upload them--if we haven't gotten them yet let me know and I'll check with MM.

**Comment by JSmith92** [comment]
I don't believe we ever got her videos. Can you get them from her and send it to us?

**Comment by loristokes** [comment]
I just forwarded you the email

**Comment by tiagodcosta** [comment]
Fixed with f6b2640972379841ce3839854ff54eb076e96fd4
