### ISSUE TITLE
Make CSS of student info modal window consistent with other modal windows

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game#358]

**Comment by aarthyadityan** [comment]
Also, this happens at lower browser widths 
<img width="376" alt="2016-12-28 11 51 10 pm" src="https://cloud.githubusercontent.com/assets/21074048/21528432/8a7d32da-cd58-11e6-8937-29a4843caa93.png">

**Comment by tiagodcosta** [comment]
Fixed with 908f8b15b5b3c6e84b2087c6c91b15b2484c365e
