### ISSUE TITLE
Does 'Send' make sense on the assessment screen before the review?

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game#388]
<img width="1203" alt="2017-01-03 03 04 54 pm" src="https://cloud.githubusercontent.com/assets/21074048/21603855/238b297a-d1c6-11e6-9cbd-a9a91fdc9139.png">
<img width="1241" alt="2017-01-03 03 06 13 pm" src="https://cloud.githubusercontent.com/assets/21074048/21603869/326b7c9c-d1c6-11e6-97e0-097f31bac2b8.png">
 'Send' might make more sense after reviewing your answer

**Comment by JSmith92** [comment]
I agree. Jay suggested that we put it there so it looks like a real email layout. I will discuss this with him and get back to you.

**Comment by JSmith92** [comment]
He suggested a "Save Draft" button and then on the review screen "Send" button instead of "Submit." Does this work for you?

**Comment by aarthyadityan** [comment]
Sounds good to me!
