### ISSUE TITLE
intermediate boss screen

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#405]
The boss says to make the calls, but the buttons below his text are "Back" and "Put the email in order". There's no "make a phone call" button, and it's not obvious that you need to go over and click the phone. We need some directional text to tell them to make the calls, like "Click the phone to make the phone calls."

**Comment by JSmith92** [comment]
Is "Click the phone on your left to make phone calls" okay? or "Click the phone on your left to make phone calls before proceeding to the email." Or is "Click the phone to make the phone calls" good enough?

**Comment by loristokes** [comment]
I think "Click the phone on your left to make phone calls and get Keynote Information."
