### ISSUE TITLE
Third keynote?

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#407]
I wrote these and I still can't find the third keynote! I got one keynote from Donald, and one from the Asst Manager. Where/what is the third?

**Comment by JSmith92** [comment]
Its in the Asst Manager's Conversation. You have to ask about Adina before asking where why she was away. I did this as a bonus keynote and to encourage users to try other route in the conversation.

**Comment by loristokes** [comment]
Oh; I see--thanks
