### ISSUE TITLE
intermediate email goes to save too quickly

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#436]
When Julie played it, she went through the 4 tabs but then instead of getting the 5th, to put in the sign-off, the game told her she was all done and she should submit the email.

![screen shot 2017-01-05 at 1 57 57 pm](https://cloud.githubusercontent.com/assets/24571312/21693467/10efa63a-d34f-11e6-9791-7e60216a5132.png)

**Comment by JSmith92** [comment]
I think she just missed the box. The game recorded that she dropped her option somewhere and that it should proceed.
We found this problem and have fixed it so that your chosen option has to be in the answer area to proceed.
