### ISSUE TITLE
clicking the phone is still delayed

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#437]
When Julie played, she had a long pause between clicking the phone and getting to the dialog screen. I know we've been working on this; hopefully we can get a fix going.

**Comment by tiagodcosta** [comment]
Probably this delay happened because the phone image was too big - almost 2000px. I reduced it to 150px in a commit last night 1901fc42e7b219b2551ce64ac0d8779d3a297b2f

**Comment by JSmith92** [comment]
We'll send another update for her to try out tonight.
