### ISSUE TITLE
Text not shown when being dragged in Safari

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game#488]

**Comment by aarthyadityan** [comment]
Try using setDragImage

**Comment by aarthyadityan** [comment]
For some reason, removing the css style 'transform: translate(-36%, -46%);' from the class 'dd_container' fixes this (line 11 in 'drag-and-drop.css'). @tiagodcosta, can you try modifying the css to not use a transform?

**Comment by tiagodcosta** [comment]
Fixed with 14ccd8067518446be5ca064205d5a29e53f22cae
