### ISSUE TITLE
intermediate put the letter together - sign-off 2

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game#499]
Take out the initials   vjr . This is a change from Julie that forces us to change the feedback as well - REMOVE the feedback text "The initials of the person sending the letter are missing."

**Comment by JSmith92** [comment]
@aarthyadityan I removed the initials. remove the Feedback text in your version and then close this issue.

**Comment by JSmith92** [comment]
sorry, accidentally closed it.. Remember this is for module 2.
